name: Citrus-os
description: Mein massgeschneidertes Linux basierend auf Fedora Kinoite
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 44

modules:
  - type: rpm-ostree
    repos:
      - copr:ilyaz/LACT
    install:
      - lact            
      - mangohud         
      - goverlay         
      - ksystemlog       
      - abrt-desktop     
      - lutris          

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub"
      install:
        - com.usebottles.bottles  
        - com.valvesoftware.Steam 
