name: citrus-os
description: Mein massgeschneidertes Linux basierend auf Fedora Kinoite
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 44

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/ilyaz/LACT/repo/fedora-%OS_VERSION%/ilyaz-LACT-fedora-%OS_VERSION%.repo
    install:
      - lact
      - mangohud
      - goverlay
      - ksystemlog
      - lutris

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub"
      install:
        - com.usebottles.bottles  
        - com.valvesoftware.Steam 
