name: citrus-os-nvidia
description: Mein massgeschneidertes Linux fuer NVIDIA
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 44

modules:
  - type: rpm-ostree
    install:
      - mangohud
      - goverlay
      - ksystemlog
      - lutris
      - gnome-logs
      - plasma-discover
      - file-roller
      
  - type: default-flatpaks@v1
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub"
      install:
        - com.usebottles.bottles
        - com.valvesoftware.Steam
        - com.leinardi.gwe
      args:
        - --filesystem=home
        - --filesystem=host